version: "3.7"
services:
  superset:
    image: apache/superset
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_ENV=production
      - SUPERSET_SECRET_KEY=clave_ultra_secreta_superlarga_12345678!@#
      - PYTHONPATH=/app/pythonpath
    volumes:
      - ./superset_home:/app/superset_home
      - ./superset_config.py:/app/pythonpath/superset_config.py
    command: >
      /bin/bash -c "
      superset db upgrade &&
      superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin &&
      superset init &&
      gunicorn --bind 0.0.0.0:8088 'superset.app:create_app()'"
